name: Deploy Enterprise Stacks

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Make Shell Scripts Executable
        run: chmod +x *.sh

      - name: Deploy Infrastructure Stack
        run: ./create-infra.sh

      - name: Deploy Compute and DB Stack
        env:
          DB_PASSWORD: "SuperSecretDBPass2026!"
        run: |
          sed -i 's/KEY_PAIR_NAME="YourKeyPairName"/KEY_PAIR_NAME="EC2Key"/' create-vm-and-db.sh
          ./create-vm-and-db.sh
